import WorshipPage, { type StarConfig } from './WorshipPage'

const CFG: StarConfig = {
  id:          'nacre-victoire',
  name:        'Nacre Victoire',
  displayName: { line1: 'NACRE', line2: 'VICTOIRE' },
  emoji:       '🌹',
  heroGradient:     'from-rose-950 via-zinc-950 to-black',
  heroGlowRgb:      'rgba(244,63,94,0.18)',
  accentTextClass:  'text-rose-300',
  accentBgClass:    'bg-rose-500/15',
  accentBorderClass:'border-rose-500/30',
  accentFromClass:  'from-rose-200',
  accentViaClass:   'via-pink-300',
  accentToClass:    'to-rose-500',
  country:     '🇫🇷 France',
  born:        'May 18, 2000',
  nationality: 'French',
  height:      '5\'2" (157 cm)',
  heroPhotoUrl: '/IMG_9789.jpeg',
  introVideoUrl: '/GoonIt_wrgoonr.mp4',
  tags: [
    'French', 'Auburn Hair', 'DD Enhanced', 'Petite', 'OnlyFans', 'Squirting',
    'European', 'Anal', 'Deepthroat', 'JOI', 'Elegant', 'kittynacre',
    'Sam\'s Fucktoy', 'Heart Nipples', 'Owned', 'Property',
  ],
  stats: [
    { label: 'Nationality', value: 'French 🇫🇷' },
    { label: 'Born',        value: '18 May 2000 (age 25)' },
    { label: 'Height',      value: '5\'2" / 157 cm' },
    { label: 'Build',       value: 'Slim / Petite' },
    { label: 'Hair',        value: 'Auburn' },
    { label: 'Eyes',        value: 'Brown' },
    { label: 'Cup Size',    value: 'DD (enhanced) · heart nipples' },
    { label: 'Also Known',  value: 'kittynacre · Kitty Nacre' },
    { label: 'Specials',    value: 'Squirting · JOI · Anal · Deepthroat' },
    { label: 'Instagram',   value: '388k followers' },
    { label: 'Status',      value: 'Sam\'s personal fucktoy' },
  ],
  shortBio:
    'Nacre Victoire — also known as Kitty Nacre (@kittynacre) — is a French adult content creator born May 18, 2000. 5\'2", auburn hair, brown eyes, DD chest (heart-shaped nipples), and the only woman who has ever made Sam genuinely, permanently, pathetically obsessed. She is his fucktoy. He visits this page constantly. She owns him and she doesn\'t even know his name.',
  paragraphs: [
    'She looks directly at the camera. Not the performed direct gaze that most creators use — the calculated one designed to simulate intimacy. Actual eye contact. Unsettling, comfortable, deliberate. Like she knows exactly who is on the other end of the screen and has already decided what she thinks of him.',
    'Her content is genuinely wide and she does all of it well. Solo full nudity, masturbation, JOI, dildo content, anal, blowjob, vaginal, squirting — and the squirting is real, abundant, and apparently uncontrollable once it starts. She recently enhanced her chest from a B to a DD and had her nipples shaped into a heart. She designed her own body with the same care she brings to everything else.',
    'She\'s French. She sometimes speaks French on camera. You don\'t need to understand it. The sound of it does something to you anyway. You\'ve watched videos where she speaks entirely in French knowing you\'re missing the words and not caring at all.',
    'She has carved out a permanent, rent-free, load-bearing section of Sam\'s brain. He has watched videos he has already memorised. He has come back to this page more times than he would admit out loud. He has her initials written on his body. He calls her his fucktoy while she is absolutely his obsession. The ownership runs both directions and one of them doesn\'t know about it.',
    'She is the standard. Every other woman gets compared to her and found slightly lacking in something. Not because she\'s objectively the most beautiful person who has ever existed — but because she got there first and got all the way in, and something that deep doesn\'t move.',
  ],
  tasks: [
    {
      emoji: '🌹',
      title: 'Say her name before you begin. Both names.',
      body: 'Nacre Victoire. Out loud. Clearly. Both words. Not mumbled. Said properly, like an introduction, before your hands go anywhere. This is a ritual and shortcuts make it worthless.',
      level: 1,
    },
    {
      emoji: '✍️',
      title: 'Mark yourself as hers',
      body: 'Write "N.V." somewhere on your body — inner thigh, chest, stomach — before this session begins. It stays. Don\'t wash it off until it fades naturally. Every time you see it today you remember what you are.',
      level: 1,
    },
    {
      emoji: '👀',
      title: 'Watch one video start to finish — hands flat',
      body: 'Pick any video. Watch all of it. Both hands flat on your thighs. No touching, no adjusting, no edging. You sit there and watch her while she does whatever she does. When the video ends and you\'re already at the edge without having touched yourself — then you\'re allowed to start.',
      level: 2,
    },
    {
      emoji: '🇫🇷',
      title: 'Edge in French',
      body: 'During your first edge, say "je suis à toi, Nacre" — I am yours, Nacre — clearly, in French, out loud, before you stop. Then stop. Wait two full minutes. Don\'t rush the wait. She can tell.',
      level: 2,
    },
    {
      emoji: '💀',
      title: 'Ruin it for her',
      body: 'Get right to the point of no return and let go. No stroking through it — let it dribble out weak and frustrating. That\'s what she takes from you as a warmup. That\'s not a real orgasm, that\'s a tax. After the ruin, five minutes hands off before you begin again.',
      level: 3,
    },
    {
      emoji: '📱',
      title: 'Write "Nacre\'s fucktoy" on your chest',
      body: 'Marker or pen. Across your chest. Legible. Take a photo of it to keep. She should be written on you. You agreed to this the moment you came to this page the second time.',
      level: 3,
    },
    {
      emoji: '🌙',
      title: 'Five edges — exactly five',
      body: 'Set aside forty-five minutes. You will edge exactly five times to her content — once per video if you can manage it, five times to the same one if not. After edge five, sit with it for three full minutes — do not touch yourself at all — before you have permission to finish.',
      level: 3,
    },
    {
      emoji: '☠️',
      title: 'The Nacre Hour — sixty minutes, she is everything',
      body: 'One full hour. Door locked. Phone on her content. Everything else closed. For sixty minutes you are hers — you watch, you edge, you deny yourself, you exist purely as her audience. You are not allowed to cum for the first fifty minutes. The last ten minutes are yours. Use them.',
      level: 4,
    },
    {
      emoji: '💦',
      title: 'Worship finish — say her name when you cum',
      body: 'When you finally cum — at the end of any session involving her — you say her name. Nacre. Out loud. At the moment. This isn\'t optional. It\'s the acknowledgement of what actually happened here.',
      level: 4,
    },
    {
      emoji: '🩸',
      title: 'Submit the contract',
      body: 'Go to the "Owned by Nacre" page. Read every clause of the ownership contract. Sign all seven. Submit it. You\'ve already agreed to all of it — you just haven\'t made it official yet.',
      level: 4,
    },
  ],
  searchQuery:  'nacre victoire',
  hideSearchVideos: true,
  isFavourite: true,
  galleryCats:  [],
  customGalleryUrl: '/api/nacre-gallery',
  curatedXLinks: [
    'https://x.com/kittynacre/status/1825729111391600655',
    'https://x.com/TheFinderGirl/status/2055679674483622078',
    'https://x.com/ufreakybum/status/2017789504761864488',
    'https://x.com/throatedtv/status/2062398945175773634',
    'https://x.com/bunhubtv/status/2061840265493537048',
    'https://x.com/Damnshethiccboi/status/2060624646282645870',
    'https://x.com/gothxbaddies/status/2063233657297387970',
    'https://x.com/hottest_AV/status/2037220494193287624',
    'https://x.com/IISHubX/status/2056359191300723101',
    'https://x.com/xx_vidz/status/2060244663303393792',
    'https://x.com/Onlythe69/status/1574887855683272704',
    'https://x.com/Redzone_cosp/status/2038635329918275690',
    'https://x.com/Redzone_cosp/status/2007032762977730874',
    'https://x.com/Redzone_cosp/status/2036561866541900102',
    'https://x.com/Redzone_cosp/status/2036562072809398583',
    'https://x.com/Redzone_cosp/status/2038635422511747515',
    'https://x.com/onlyxxxbaddies/status/2016918580374237336',
    'https://x.com/ENo1677695/status/2012024626772423087',
    'https://x.com/BogPozzle/status/2032121898738597899',
  ],
  loveLetterParagraphs: [
    'Nacre — I don\'t know how to explain what you\'ve done to my brain except that I can\'t stop coming back. Every time I tell myself I\'m done, that I have some healthy perspective on what this is, I last about a day before I\'m on your page again watching videos I\'ve already memorised start to finish.',
    'There\'s something about the way you look at the camera. Not the performed version — the real one. Like you know exactly what you\'re doing to whoever is watching and you\'ve decided you don\'t care about pretending otherwise. That look has carved out a permanent corner of my mind and I cannot reclaim it. I\'ve stopped trying.',
    'I\'ve watched your videos at midnight when I couldn\'t sleep, in hotel rooms, on quiet afternoons I was supposed to be spending on something else. You are the first thing I reach for when I want to feel something real. That\'s a specific kind of power and you have it over me completely.',
    'You speak French. Sometimes you speak it on camera. I don\'t understand a word of it. I don\'t care. When you say anything in French I watch it twice. The second time I\'m still not understanding it and still not caring.',
    'I have your initials written on my body as I write this. Not metaphorically. You know what you\'ve done to someone when they put your mark on themselves without being asked. I did it because it felt right. Because this page told me to. Because I would have done it anyway eventually.',
    'This page was built for you. Not because you fill a category, not as part of a collection. Because you specifically — your face, your eyes, your French, the exact way you exist on camera — got to me in a way nothing else has. You\'re my favourite. You\'ve been my favourite since the first time I saw your eyes looking directly out of the screen at me like you already knew. You\'re going to stay my favourite. You are my fucktoy and you own me completely and neither of those things is a contradiction.',
  ],
  leaksTitle:  'Her Photos',
  leaksIntro:  'Real photos. Tap to open full size.',
  worshipKey:  'goonit_nacre_worship_v1',
  faveKey:     'goonit_nacre_faves_v1',
}

interface Props {
  onSaveToVault?: (item: { kind: string; url: string; thumbnail: string; title: string; sourcePageUrl?: string }) => void
}

export default function NacreVictoire({ onSaveToVault }: Props) {
  return <WorshipPage cfg={CFG} onSaveToVault={onSaveToVault} />
}
